### ISSUE TITLE
Handle/suppress socket errors in UdpClient

### ISSUE THREAD

**Issue by EvanDarwin** [corley/influxdb-php-sdk#27] opened 2015-06-03 18:02 UTC
There's no point in using UDP if it's going to throw an error if the InfluxDB database is down.

**Message: socket_sendto(): unable to write to socket [64]: Host is down**
```
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'socket_sendto()...', '...', 37, Array)
#1 /.../vendor/corley/influxdb-sdk/src/InfluxDB/Adapter/UdpAdapter.php(37): socket_sendto(Resource id #350, '[{"name":"www.r...', 135, 0, '172.16.1.121', 4444)
#2 /.../vendor/corley/influxdb-sdk/src/InfluxDB/Client.php(80): InfluxDB\Adapter\UdpAdapter->send(Array, false)
#3 /.../public/index.php(89): InfluxDB\Client->mark('www.request', Array)
#4 /.../server.php(21): require_once('/Users/eedarwin...')
#5 {main}
```

**Comment by wdalmut** [comment] 2015-06-03 20:02
Thanks for your report.

The problem is not related to UDP/IP but hostname resolution.

I add a test case in order to show this.

You can resolve your hostname?

**Comment by wdalmut** [comment] 2015-06-03 20:04
Expose this problem in #28

**Comment by EvanDarwin** [comment] 2015-06-03 20:07
Well I was using an IP address but I can still see this happening, as long as it can be automatically handled by the SDK then I won't have to have like 90 try/catches in my code.

**Comment by wdalmut** [comment] 2015-06-03 20:09
Strange that happening with IP addresses we shutdown our monitor sometime and our application never shows this error.

I try to replicate your error with another testcase

**Comment by wdalmut** [comment] 2015-06-03 20:13
@EvanDarwin 

You are prepare the client using something like this:

        $options = new Options();
        $options->setHost("55.44.22.11"); // Your IP directly
        $options->setUsername("my-user");
        $options->setPassword("my-password");
        $options->setPort(4444); // Your port

        $adapter = new UdpAdapter($options);
        $object = new Client();
        $object->setAdapter($adapter);

        $object->mark("udp.test", ["mark" => "element"]);

Right?

**Comment by EvanDarwin** [comment] 2015-06-03 20:14
Yup, exactly like that.

```php
    $options = new \InfluxDB\Options();

    // Configure options
    $options->setHost(env('INFLUXDB_HOST', '172.16.1.182'));
    $options->setPort(4444);
    $options->setDatabase(env('INFLUXDB_DB', '...'));
    $options->setUsername(env('INFLUXDB_USER', 'root'));
    $options->setPassword(env('INFLUXDB_PASS', 'root'));

    $httpAdapter = new \InfluxDB\Adapter\UdpAdapter($options);

    $client = new \InfluxDB\Client();
    $client->setAdapter($httpAdapter);
```

**Comment by wdalmut** [comment] 2015-06-03 20:16
and the `env` function will reply with just the ip string `172.16.1.182` or another one right?

**Comment by wdalmut** [comment] 2015-06-03 20:20
I have added your scenario in our testsuite

https://github.com/corley/influxdb-php-sdk/commit/995f1038de3de3edf340ae0bdb1de4a5f04416a9

I run it locally and it pass locally (i wait also for travis-ci)...

**Comment by wdalmut** [comment] 2015-06-03 20:37
https://travis-ci.org/corley/influxdb-php-sdk/jobs/65307363

the only failing test is on not resolving hostnames and not unreachable servers.

i will go more deeply on this

**Comment by wdalmut** [comment] 2015-06-20 07:33
Any on this?

**Comment by EvanDarwin** [comment] 2015-06-20 20:28
PR #31!

**Closed** 2015-06-21 15:52 UTC
Labels: question
